### PR TITLE
FHG-5328 Delete sessions via query prameter

### PR DESCRIPTION
**Pull request by Top-Cat**

### CODE REVIEW

**Review by AaronJY — APPROVED** [review]

**Review by Zac-Digital — APPROVED** [review]

**Comment by AaronJY** [comment]
@tomadams-dfe which ticket does this relate to?

**Comment by Top-Cat** [comment]
@AaronJY 
> @tomadams-dfe which ticket does this relate to?

Don't know who tomadams is but the ticket number is right there 
Screenshot 2024-06-12 at 09 53 55

**Comment by AaronJY** [comment]
@Top-Cat Cool thanks! Can we stick them in the title too please; it makes searching for PRs for a specific ticket much easyer

**Comment by tomadams-dfe** [comment]
I think I've been added to this ticket by mistake - not my project/area

**Pull request merged**
